sudo: false

language: android

android:
  components:
    - build-tools-26.0.2
    - android-27

env:
  global:
    - ORG_GRADLE_PROJECT_cdvMinSdkVersion=20

install:
  - nvm install 10
  - npm install

script:
  - npm run pretest
  - npx ionic cordova build android
  - ls -l platforms/android/app/build/outputs/apk/debug/app-debug.apk
